version: "3.8"
services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault-dev
    restart: always
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - 8200:8200
    networks:
      - vault-dev-net
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -dev

networks:
  vault-dev-net:
    name: vault-dev-net