version: "3.8"
services:
  vault:
    image: hashicorp/vault
    container_name: vault
    restart: always
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_ADDRESS: http://127.0.0.1:8200
      VAULT_API_ADDR: http://127.0.0.1:8200
    ports:
      - 8200:8200
    networks:
      - vault-net
    volumes:
      - ./config/vault.json:/config/vault.json
      - vault-data:/vault/data
      - vault-logs:/vault/logs
      - vault-config:/vault/config
      - vault-policies:/vault/policies
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/config/vault.json

networks:
  vault-net:
    name: vault-net
    driver: bridge

volumes:
  vault-data:
    name: vault-data
  vault-logs:
    name: vault-logs
  vault-config:
    name: vault-config
  vault-policies:
    name: vault-policies