version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - mysql-net
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  mysql-net:
    name: mysql-net

volumes:
  mysql-data:
    name: mysql-data