version: "3.8"
services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
    - type: volume
      source: data
      target: /var/lib/mysql

volumes:
  data: