version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    volumes:
    - type: volume
      source: zookeeper-data
      target: /var/lib/zookeeper/data
    - type: volume
      source: zookeeper-log
      target: /var/lib/zookeeper/log
    - type: volume
      source: zookeeper-secrets
      target: /etc/zookeeper/secrets
  
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on: 
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
    - type: volume
      source: data
      target: /var/lib/kafka/data
    - type: volume
      source: secrets
      target: /etc/kafka/secrets
      
volumes:
  data:
  secrets:
  zookeeper-data:
  zookeeper-log:
  zookeeper-secrets: