version: "3.8"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    volumes:
    - type: volume
      source: zookeeper_data
      target: /var/lib/zookeeper/data
    - type: volume
      source: zookeeper_log
      target: /var/lib/zookeeper/log
    - type: volume
      source: zookeeper_secrets
      target: /etc/zookeeper/secrets
  
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    depends_on: 
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
    volumes:
    - type: volume
      source: data
      target: /var/lib/kafka/data
    - type: volume
      source: secrets
      target: /etc/kafka/secrets
      
volumes:
  data:
  secrets:
  zookeeper_data:
  zookeeper_log:
  zookeeper_secrets: