version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
    - type: volume
      source: data
      target: /var/lib/postgresql/data

volumes:
  data:
