version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - pg-net
    volumes:
      - pg-data:/var/lib/postgresql/data

networks:
  pg-net:
    name: pg-net
    driver: bridge

volumes:
  pg-data:
    name: pg-data
