version: "3.8"
services:
  artemis:
    image: apache/activemq-artemis:latest
    container_name: artemis
    restart: unless-stopped
    environment:
      ARTEMIS_USER: user
      ARTEMIS_PASSWORD: password
    ports:
      - 8161:8161
      - 61616:61616
    networks:
      - artemis-net
    volumes:
      - artemis-data:/var/lib/artemis-instance

networks:
  artemis-net:
    name: artemis-net

volumes:
  artemis-data:
    name: artemis-data
