version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always 
    entrypoint: redis-server --appendonly yes --maxmemory 128mb --maxmemory-policy allkeys-lru
    ports:
      - 6379:6379
    networks:
      - redis-net
    volumes:
      - redis-data:/data

networks:
  redis-net:
    name: redis-net
    driver: bridge

volumes:
  redis-data:
    name: redis-data